---
_sg_meta:
  type: "config"
  config_version: 2
sg_config:
  dynamic:
    authc:
      basic_internal_auth:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          challenge: true
          type: "basic"
        authentication_backend:
          type: "internal"